# -*- coding: utf-8 -*-
"""correctedHamiltonian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uh7clKLswRIUywXj9ln7rJDd3jxY8Zl
"""

#for a bit of context, the goal was to derive a conserved Hamiltonian, H~ for H=0.5mv^2+0.5kx^2, where x,v obey the semi-implicit Euler update equations, where we require H(t+dt)=H(t) for all dt
#this was done by (after lots of silly error...) taking H_1-H_0 and expressing it in a way that made it clear what H~ was, since H~=H_i+alpha, for some alpha, and you can't trivially evaluate it to get alpha
#to be precise, if you try, you just get alpha(t+dt)-alpha(t) which, doesn't really give alpha, and thus no H~. The trick is, as far as I can tell, use the Euler update equations only TWICE - x, v once each

import numpy as np
import matplotlib.pyplot as plt

x0=5
v0=10
dt=0.1; t=np.empty(N);t[0]=0
N=500
m=1
k=1

H=np.empty(N)
Hc=np.empty(N)
x=np.empty(N);x[0]=x0
v=np.empty(N);v[0]=v0

H[0]=0.5*m*v[0]**2 + 0.5*k*x[0]**2
Hc[0]=0.5*m*v[0]**2 + 0.5*k*x[0]**2 - 0.5*dt*k*v[0]*x[0]
print(H[0])

for i in range(N-1):
  t[i+1]=t[i]+dt
  v[i+1]=v[i]+(-k/m)*x[i]*dt
  x[i+1]=x[i]+v[i+1]*dt

  H[i+1]=0.5*m*v[i+1]**2 + 0.5*k*x[i+1]**2

  Hc[i+1]=0.5*m*v[i+1]**2 + 0.5*k*x[i+1]**2 - 0.5*dt*k*v[i+1]*x[i+1]

  if i % 50 == 0:
    print("non-corrected",H[i])
    print("corrected",Hc[i])

plt.plot(Hc,t)
plt.plot(H,t)